<?php

namespace Arcanys\EasyAppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntitychecknumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntitychecknumRepository extends EntityRepository
{
}
