<?php

namespace Arcanys\EasyAppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InvoiceImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceImagesRepository extends EntityRepository
{
    public function countByInvoiceId($invoiceId)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('count(u.id)');
        $qb->from($this->_entityName, 'u')
            ->where('u.idInvoice = :invoiceId')
            ->setParameters(['invoiceId' => $invoiceId]);

        return $qb->getQuery()->getSingleScalarResult();
    }

}
