<?php

namespace Arcanys\EasyAppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserimageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserimageRepository extends EntityRepository
{
}
