Arcanys\EasyAppBundle\Entity\Entitycomments:
    type: entity
    table: null
    repositoryClass: Arcanys\EasyAppBundle\Entity\EntitycommentsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        entityId:
            type: integer
            column: entity_id
        comments:
            type: text
        status:
            type: integer
        dateadded:
            type: datetime
            nullable: false
        dateupdated:
            type: datetime
            nullable: true
    lifecycleCallbacks:
            prePersist: [ prePersist ]
            preUpdate: [ preUpdate ]
