Arcanys\EasyAppBundle\Entity\Revenuewire:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        dateadded:
            type: string
            nullable: true
        entityId:
            type: string
            column: entity_id
        entitybanknameId:
            type: integer
            column: entitybankname_id
        amount:
            type: string
            length: 255
        wiretype:
            type: integer
            column: type
        status:
            type: integer
            nullable: true
        description:
            type: text
        upltoken:
            type: string
            length: 255
        company:
            type: string
            column: company_id
    lifecycleCallbacks: {  }